#!/bin/sh

PATH=/usr/sbin:/usr/bin:/sbin:/bin
export PATH

mount -t sysfs none /sys
mount -t tmpfs none /var
mount -t tmpfs none /tmp
mount -t proc none /proc
mkdir /dev/pts
mount -t devpts none /dev/pts
mount -t debugfs none /sys/kernel/debug

depmod

modprobe ps2fb mode_option=1920x1080p@60

modprobe sif
modprobe iop-memory
modprobe iop-module
modprobe iop-irq

modprobe sd_mod
modprobe ohci-ps2
modprobe ums-usbat
modprobe usbhid
modprobe hid-generic

grep machine </proc/cpuinfo | sed 's/[[:space:]]\+//'
uname -a

sh

while :
do
	sleep 1
done
