#!/bin/bash

export ARCH=mips
export CROSS_COMPILE=mipsr5900el-unknown-linux-musl-
export INSTALL_MOD_PATH=../initramfs/ps2
export INSTALL_MOD_STRIP=1

git clone https://github.com/frno7/linux --depth 1

(cd linux &&
 make -j $(getconf _NPROCESSORS_ONLN) ps2_defconfig &&
 make -j $(getconf _NPROCESSORS_ONLN) oldconfig &&
 make -j $(getconf _NPROCESSORS_ONLN) vmlinux &&
 make -j $(getconf _NPROCESSORS_ONLN) modules &&
 make -j $(getconf _NPROCESSORS_ONLN) modules_install &&
 make -j $(getconf _NPROCESSORS_ONLN) vmlinuz)
